"""empty message

Revision ID: 487b23c4899b
Revises: c23c480abaf3
Create Date: 2023-02-28 18:45:01.620957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487b23c4899b'
down_revision = 'c23c480abaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
